spring.application.name=pokedex-api
spring.datasource.url=jdbc:postgresql://localhost:5432/pokedex_db
spring.datasource.username=usuario_dev
spring.datasource.password=senha_forte
spring.jpa.hibernate.ddl-auto=update
