POST http://localhost:8080/pokemons
Content-Type: application/json


{
  "nome": "Squirtle",
  "tipo": "Agua",
  "nivel": 16,
  "descricao": "é um Pokémon do tipo Agua (#0007 na pokedéx) ."
}

### Deletar
DELETE http://localhost:8080/pokemons/7
